# Read the documentation: https://symfony.com/doc/current/bundles/FOSCKEditorBundle/index.html

twig:
    form_themes:
        - '@FOSCKEditor/Form/ckeditor_widget.html.twig'

fos_ck_editor:
    configs:
        main_config:
            toolbar:
                - { 
                    name: "styles", 
                    items: ['Bold', 'Italic', 'Underline', 'Strike', 'Blockquote', '-', 'Link', '-', 'RemoveFormat', '-', 'NumberedList', 'BulletedList', '-', 'Outdent', 'Indent', '-', '-', 'JustifyLeft', 'JustifyCenter', 'JustifyRight', 'JustifyBlock', '-', 'Table', '-', 'Styles', 'Format','Font','FontSize', '-', 'TextColor', 'BGColor', 'Source', 'Image'] 
                }
            filebrowserBrowseRouteParameters: []
    toolbars:
        configs:
            custom_toolbar_1: [ "@document", "/", "@link" , "/", "@tool" ]
            note_contact_toolbar:
                - { 
                    name: "styles", 
                    items: ['Bold', 'Italic', 'Underline', 'Strike', '-', 'Link', 'NumberedList', 'BulletedList', '-', 'Styles', 'Format','Font','FontSize', '-', 'TextColor'] 
                }
            custom_config:
                toolbar: [
                    { name: 'clipboard', items: ['Cut', 'Copy', 'Paste', 'PasteText', 'PasteFromWord', '-', 'Undo', 'Redo'] },
                    { name: 'editing', items: ['Scayt'] },
                    { name: 'links', items: ['Link', 'Unlink', 'Anchor'] },
                    { name: 'insert', items: ['Image', 'Table', 'HorizontalRule', 'SpecialChar'] },
                    { name: 'tools', items: ['Maximize'] },
                    { name: 'document', items: ['Source'] },
                    { name: 'basicstyles', items: ['Bold', 'Italic', 'Underline', 'Strike', '-', 'RemoveFormat'] },
                    { name: 'paragraph', items: ['NumberedList', 'BulletedList', '-', 'Outdent', 'Indent', '-', 'Blockquote', '-', 'JustifyLeft', 'JustifyCenter', 'JustifyRight', 'JustifyBlock'] },
                    { name: 'styles', items: ['Styles', 'Format'] }
                ]
                uiColor: "#d3d3d3"
                height: 400
                resize_enabled: true
                removePlugins: 'elementspath'
                extraPlugins: 'divarea,tab'

        items:
            document: [ "Source", "-", "Save" ]
            link:     [ "Anchor" ]
            tool:     [ "Maximize" ]
